### PR TITLE
Implement duplicate() for Command

### PR DESCRIPTION
**Pull request by murkle**
* format code and clean up
* move Commands to own classes
* implement duplicate() for all Commands (instead of clone)
* rename clone() to duplicate for Atoms (preparation for next step)

### CODE REVIEW

**Comment by sylvestre** [comment]
Did you update the changelog? thanks for the work!

**Comment by murkle** [comment]
Sorry, I think there were some files missing. Should be OK after the next two commits
(also xarrows now drawn as one object)

**Comment by murkle** [comment]
Once everything's merged, this will be the full changelog:

Changes from JLM v1

Major:
* Native cross-platform support (Java JRE, HTML5, Android, iOS)
* Editor
* Improved display of “big brackets” and stretchy “xarrows” (plus some new “x” commands)
* Faster re-written parser
* All XML removed (smaller size & faster startup time)
* MHChem compatibility added (\ce)
* Serialize better to Uncode eg
	TeXFormula tf = new TeXFormula("a\\geq b \\leq \\alpha");
String output = new TeXAtomSerializer(null).serialize(tf.root);





New commands:
* \imagebasesixtyfour (works across all platforms, unlike \includegraphics)
* \cellcolor eg
{\begin{array}{|l|l|}\hline \cellcolor{#FFEFD5}{1}&\cellcolor{#FF0000}{3} \\ \hline \cellcolor{#0000FF}{2}&\cellcolor{#BFFF00}{4} \\ \hline \end{array}}
* \ce (for MHChem - also \mathchoice, \mskip, \lower, \raise, \mkern)
* \jlmcursor and \jlmselection (for editor)
* \cancel, \bcancel, \xcancel
* \xleftrightarrows, \xrightleftarrows, \xleftharpoondown, \xleftharpoonup, \xleftrightharpoons, \xleftrightarrow, \xrightharpoondown, \xrightharpoonup, \xrightleftharpoons, \xhookleftarrow, \xhookrightarrow, \xmapsto, \xlongequal
* \$ \dollar \& \%
* \unicode (see http://docs.mathjax.org/en/latest/tex.html)
* \dbox \cornersize, \the, \enskip

Minor Changes
* Greek/CyrillicRegistration removed
* Switch to more modern Java style eg using Enum instead of int
* Removed use of clone() and Java Reflection
* \raisebox works better
* \char works for high Unicode characters eg \sqrt{\frac{\char{128512}}{2}}

**Comment by sylvestre** [comment]
Impressive work, bravo!

**Comment by murkle** [comment]
HTML5 now committed! Compile with GWT 2.8.2 -> https://test.geogebra.org/~mike/jsJLM/inlineTest.html

**Pull request merged**
