### PR TITLE
Jlatexmath maven

### PR DESCRIPTION
**Pull request by opcodevoid**

### CODE REVIEW

**Comment by davidmoten** [comment]
yes please!

**Comment by davidmoten** [comment]
I'd love to see standard maven structure too so that I can import this project as a maven project into Eclipse IDE easily and run Example* without any configuring.

src/main/java
src/main/resources
src/test/java (put tests in here later but initially put Example*.java)
src/test/resources (lion.png etc)

**Comment by opcodevoid** [comment]
You can import this project as a maven project with the given pom. It's just non-standard maven structure. I think the structure is not important here as long as the project gets deployed to the maven central repository and people can use it that way.

**Comment by davidmoten** [comment]
yep deployment to maven central is important I agree. If you want contributions to this project then you can enable people by adopting standard structures. I can do the conversion for you as a PR if you like for your assessment.

**Comment by opcodevoid** [comment]
Btw, see here #4

**Pull request merged**
