### PR TITLE
Maven rework

### PR DESCRIPTION
**Pull request by davidmoten**
* large refactoring of the code base to use a maven multi-module build
* discussed in #6, #12 
* happy for commits to be squashed on merge!

More work will naturally follow following merge especially with .travis setup and Maven Central release automation.

### CODE REVIEW

**Comment by davidmoten** [comment]
looking at openjdk differences now

**Comment by davidmoten** [comment]
Yep openjdk and oracle jdk have slight rendering differences. I've
* inspected the images visually
* fixed the image distance function so variance between pixels is the sum of the squares of the differences of the Red, Green, Blue and Alpha values. Distance is then total variance divided by num pixels in image.
* set the threshold to 40
* TODO distance function is copied and pasted to two modules, should create a child module for the distance utility so that it is shared code

**Comment by sylvestre** [comment]
Impressive work!

**Comment by davidmoten** [comment]
Moved the image distance function used in tests in multiple modules to the core jlatexmath artifact in an `internal` package (any package labelled `internal` should not be considered part of the public API).

Squashed commits.

**Comment by calixteman** [comment]
Are you ready to merge this PR ?

**Comment by davidmoten** [comment]
>Are you ready to merge this PR ?

Yep.  There is more cleanup stuff like fixing warnings (unused code, unused imports) but I tried to limit the scope of this work to just the multi-artifact refactor and to add tests (so that I knew my work hadn't broken anything). Other fixes can wait for later PRs. I'll also need to update the docs with build instructions (not tricky `mvn clean install`), and have a chat with you about releases. Consultation with primary users about the new artifact breakdown will be good too.

**Comment by davidmoten** [comment]
In case I was ambiguous about being ready to merge, yes we are ready to merge. I'll leave it to you when you' are ready @calixteman.

**Comment by calixteman** [comment]
@davidmoten thanks for your work

**Comment by davidmoten** [comment]
no probs, thanks for yours!

**Pull request merged**
